import { LandingFooter } from "@/components/landing/landing-footer"
import { LandingNav } from "@/components/landing/landing-nav"
import { TopNav } from "@/components/navigation/top-nav"
import { getUserProfile } from "@/lib/actions/auth"
import { checkAuthStatus } from "@/lib/actions/auth-check"

export const dynamic = "force-dynamic"
export const revalidate = 0

export default async function AMLPolicyPage() {
  const auth = await checkAuthStatus()
  let userName = "User"
  let userImage = "/vibrant-street-market.png"
  if (auth.authenticated) {
    const userProfile = await getUserProfile()
    userName = `${userProfile?.profile?.first_name || ""} ${userProfile?.profile?.last_name || ""}`.trim() || "User"
    userImage = userProfile?.profile?.profile_picture_url || "/vibrant-street-market.png"
  }

  return (
    <div className="flex flex-col min-h-screen">
      {auth.authenticated ? <TopNav userName={userName} userImage={userImage} /> : <LandingNav />}
      <main className="flex-1">
        <div className="container max-w-3xl mx-auto py-10">
          <h1 className="text-3xl font-bold mb-6">Anti–Money Laundering (AML) Policy</h1>
          <p className="text-gray-700 mb-6">
            This Anti–Money Laundering Policy ("Policy") sets out the standards and procedures adopted by
            Peer Capital to prevent and detect money laundering, terrorist financing, fraud, and other
            financial crimes. Peer Capital is committed to complying with all applicable AML and
            Counter–Terrorist Financing (CTF) laws, regulations, and guidelines.
          </p>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">1. Purpose and Scope</h2>
            <p className="text-gray-700">
              This Policy applies to all users, employees, contractors, affiliates, and partners of Peer Capital
              and covers all products, services, and operations where Peer Capital is engaged.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">2. Legal and Regulatory Framework</h2>
            <p className="text-gray-700">
              Peer Capital adheres to relevant AML/CTF frameworks and guidance applicable to our operations,
              including Know Your Customer (KYC) and Customer Due Diligence (CDD) obligations, sanctions
              screening, and suspicious activity reporting requirements.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">3. Customer Due Diligence (CDD) and KYC</h2>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Collect and verify identity information (e.g., full name, date of birth, address, phone, email).</li>
              <li>Obtain and verify government–issued IDs and biometrics, where required.</li>
              <li>Verify BVN/NIN or equivalent identifiers through approved verification providers.</li>
              <li>Identify and verify beneficial owners and control persons where applicable.</li>
              <li>Assess risk profiles using a risk–based approach and apply appropriate diligence levels.</li>
            </ul>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">4. Enhanced Due Diligence (EDD)</h2>
            <p className="text-gray-700">
              For higher–risk customers, geographies, products, or transactions, Peer Capital implements EDD,
              which may include additional documentation, source of funds/wealth verification, senior
              management approval, and heightened ongoing monitoring.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">5. Ongoing Monitoring</h2>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Monitor transactions to identify unusual patterns, structuring, or suspicious behavior.</li>
              <li>Review alerts generated by screening and monitoring tools and take appropriate action.</li>
              <li>Maintain up–to–date customer information and re–verify when risk triggers are met.</li>
            </ul>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">6. Sanctions and Watchlist Screening</h2>
            <p className="text-gray-700">
              Users and transactions are screened against applicable sanctions, watchlists, PEP, and adverse
              media lists. Matches or potential matches are escalated and handled in accordance with
              regulatory expectations.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">7. Prohibited Activities</h2>
            <ul className="list-disc pl-6 text-gray-700 space-y-2">
              <li>Money laundering, terrorist financing, or evasion of sanctions.</li>
              <li>Fraud, bribery, corruption, tax evasion, or other financial crimes.</li>
              <li>Use of false or stolen identities, or forged documentation.</li>
              <li>Transactions with shell banks or anonymous accounts.</li>
            </ul>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">8. Suspicious Activity Reporting</h2>
            <p className="text-gray-700">
              Peer Capital investigates suspicious activity and, where required, reports to competent
              authorities. Users may be asked to provide additional information and should cooperate fully.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">9. Record Keeping</h2>
            <p className="text-gray-700">
              Records relating to customer identification, verification, transactions, and investigations are
              retained for the period required by law and maintained securely to preserve integrity and
              confidentiality.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">10. Risk–Based Approach</h2>
            <p className="text-gray-700">
              Controls are commensurate with identified risks. Peer Capital periodically reviews its risk
              assessments and updates controls, tools, and procedures accordingly.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">11. Training and Awareness</h2>
            <p className="text-gray-700">
              Personnel receive periodic AML/CTF training appropriate to their roles, including red flags,
              reporting obligations, and data protection responsibilities.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">12. Third–Party Relationships</h2>
            <p className="text-gray-700">
              Peer Capital conducts due diligence on partners, vendors, and payment providers and requires
              appropriate contractual assurances and controls to meet AML/CTF obligations.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">13. Governance and Oversight</h2>
            <p className="text-gray-700">
              AML compliance is overseen by designated compliance personnel and management. Material
              issues are escalated to senior leadership, and our program is reviewed periodically for
              effectiveness.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">14. Data Protection</h2>
            <p className="text-gray-700">
              Customer information collected for AML/CTF compliance is processed in line with our Privacy
              Policy and applicable data protection laws. Access is limited to authorized personnel.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">15. Violations and Enforcement</h2>
            <p className="text-gray-700">
              Violations of this Policy may result in account restrictions, suspension, termination, or
              reporting to authorities, as appropriate.
            </p>
          </section>

          <section className="space-y-3 mb-8">
            <h2 className="text-xl font-semibold">16. Updates</h2>
            <p className="text-gray-700">
              This Policy may be updated periodically. Material changes will be reflected on this page.
            </p>
          </section>

          <p className="text-gray-600 text-sm">Last updated: {new Date().toLocaleDateString()}</p>
        </div>
      </main>
      <LandingFooter />
    </div>
  )
}

